env: AGV_Dispatching

env_args:
  map_name: ''
  end_time: 435
  continuing_episode: False
  reward_alpha: 10
  reward_beta: 0
  reward_theta: 0.5
  reward_scale: True
  state_last_action: True
  state_timestep_number: False
  state_normalize: 8
  obs_instead_of_state: True
  seed: None
  heuristic_ai: False
  heuristic_rest: False
  replay_dir: ''
  replay_prefix: ''
  debug: False
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
off_pg: False